apiVersion: v1
kind: Service
metadata:
  name: ido-service
  namespace: myapp
  labels:
    app: ido-backend
spec:
  type: NodePort
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      protocol: TCP
      nodePort: 30050

  selector:
    app: ido-backend